import type { CmsData } from '../types';

/** Local seed image paths (see scripts/download-seed-images.mjs) */
const img = {
  hero: '/images/seed/hero.jpg',
  category: (slug: string) => `/images/seed/categories/${slug}.jpg`,
  product: (name: string) => `/images/seed/products/${name}.jpg`,
  offer: (name: string) => `/images/seed/offers/${name}.jpg`,
  brand: (slug: string) => `/images/seed/brands/${slug}.svg`,
};

/**
 * Development fallback data — used only when SHEETS_API_URL is not configured.
 * Replace with live Google Sheets + Cloudinary data in production.
 */
export const mockCmsData: CmsData = {
  settings: {
    businessName: 'Yash Electronics',
    tagline: 'Your Trusted Local Electronics Store',
    phone: '+91 98765 43210',
    whatsapp: '919876543210',
    email: 'info@yashelectronics.in',
    address: 'Main Market Road, Near City Bus Stand',
    city: 'Your City',
    state: 'Maharashtra',
    pincode: '400001',
    googleMapsUrl: 'https://maps.google.com',
    heroTitle: 'Electronics & Home Appliances You Can Trust',
    heroSubtitle:
      'Genuine products from Sony, Samsung, Haier, IFB, Natraj, Daikin & more. Local service, competitive pricing for families across nearby towns.',
    heroImage: img.hero,
    heroCtaText: 'Browse Products',
    heroCtaLink: '/products',
    workingHours: 'Mon–Sat: 10:00 AM – 8:00 PM | Sun: 10:00 AM – 2:00 PM',
    facebookUrl: 'https://facebook.com',
    instagramUrl: 'https://instagram.com',
    youtubeUrl: 'https://youtube.com',
  },
  categories: [
    { id: '1', name: 'LED TV', slug: 'led-tv', description: 'Smart & HD TVs', icon: 'tv', image: img.category('led-tv'), sortOrder: 1, isActive: true },
    { id: '2', name: 'Refrigerator', slug: 'refrigerator', description: 'Single & double door', icon: 'fridge', image: img.category('refrigerator'), sortOrder: 2, isActive: true },
    { id: '3', name: 'Washing Machine', slug: 'washing-machine', description: 'Front & top load', icon: 'washer', image: img.category('washing-machine'), sortOrder: 3, isActive: true },
    { id: '4', name: 'Microwave', slug: 'microwave', description: 'Solo & convection', icon: 'microwave', image: img.category('microwave'), sortOrder: 4, isActive: true },
    { id: '5', name: 'Air Fryer', slug: 'air-fryer', description: 'Healthy cooking', icon: 'air-fryer', image: img.category('air-fryer'), sortOrder: 5, isActive: true },
    { id: '6', name: 'RO System', slug: 'ro-system', description: 'Water purifiers', icon: 'water', image: img.category('ro-system'), sortOrder: 6, isActive: true },
    { id: '7', name: 'Air Conditioner', slug: 'air-conditioner', description: 'Split & window AC', icon: 'ac', image: img.category('air-conditioner'), sortOrder: 7, isActive: true },
    { id: '8', name: 'Air Cooler', slug: 'air-cooler', description: 'Desert & personal', icon: 'cooler', image: img.category('air-cooler'), sortOrder: 8, isActive: true },
    { id: '9', name: 'Gharghanti', slug: 'gharghanti', description: 'Flour mills', icon: 'mill', image: img.category('gharghanti'), sortOrder: 9, isActive: true },
    { id: '10', name: 'Gas Stove', slug: 'gas-stove', description: '2 & 4 burner', icon: 'stove', image: img.category('gas-stove'), sortOrder: 10, isActive: true },
    { id: '11', name: 'Chimney', slug: 'chimney', description: 'Kitchen chimneys', icon: 'chimney', image: img.category('chimney'), sortOrder: 11, isActive: true },
    { id: '12', name: 'Blender', slug: 'blender', description: 'Hand & jar blenders', icon: 'blender', image: img.category('blender'), sortOrder: 12, isActive: true },
    { id: '13', name: 'Mixer Grinder', slug: 'mixer-grinder', description: 'Juicer mixer grinders', icon: 'mixer', image: img.category('mixer-grinder'), sortOrder: 13, isActive: true },
  ],
  brands: [
    { id: '1', name: 'Sony', slug: 'sony', logo: img.brand('sony'), sortOrder: 1, isActive: true },
    { id: '2', name: 'Samsung', slug: 'samsung', logo: img.brand('samsung'), sortOrder: 2, isActive: true },
    { id: '3', name: 'Haier', slug: 'haier', logo: img.brand('haier'), sortOrder: 3, isActive: true },
    { id: '4', name: 'IFB', slug: 'ifb', logo: img.brand('ifb'), sortOrder: 4, isActive: true },
    { id: '5', name: 'Iwis', slug: 'iwis', logo: img.brand('iwis'), sortOrder: 5, isActive: true },
    { id: '6', name: 'CLT', slug: 'clt', logo: img.brand('clt'), sortOrder: 6, isActive: true },
    { id: '7', name: 'Trion', slug: 'trion', logo: img.brand('trion'), sortOrder: 7, isActive: true },
    { id: '8', name: 'Komfy', slug: 'komfy', logo: img.brand('komfy'), sortOrder: 8, isActive: true },
    { id: '9', name: 'Daikin', slug: 'daikin', logo: img.brand('daikin'), sortOrder: 9, isActive: true },
    { id: '10', name: 'Voltas', slug: 'voltas', logo: img.brand('voltas'), sortOrder: 10, isActive: true },
    { id: '11', name: 'Mitsubishi Heavy', slug: 'mitsubishi-heavy', logo: img.brand('mitsubishi-heavy'), sortOrder: 11, isActive: true },
    { id: '12', name: 'Blue Star', slug: 'blue-star', logo: img.brand('blue-star'), sortOrder: 12, isActive: true },
    { id: '13', name: 'Natraj', slug: 'natraj', logo: img.brand('natraj'), sortOrder: 13, isActive: true },
    { id: '14', name: 'Ivas', slug: 'ivas', logo: img.brand('ivas'), sortOrder: 14, isActive: true },
  ],
  products: [
    {
      id: 'p1',
      name: 'Sony Bravia 55" 4K Ultra HD Smart LED TV',
      slug: 'sony-bravia-55-4k-smart-led-tv',
      brand: 'Sony',
      brandSlug: 'sony',
      category: 'LED TV',
      categorySlug: 'led-tv',
      modelNumber: 'KD-55X75L',
      description: 'Experience stunning 4K picture quality with Google TV, Dolby Audio and seamless streaming.',
      specifications: '{"Screen Size":"55 inch","Resolution":"4K Ultra HD","Smart TV":"Google TV","Refresh Rate":"60Hz","Warranty":"1 Year"}',
      mrp: 89990,
      offerPrice: 74990,
      images: [img.product('sony-tv-1'), img.product('sony-tv-2')],
      isFeatured: true,
      isActive: true,
      createdAt: '2026-01-15',
      updatedAt: '2026-03-01',
    },
    {
      id: 'p2',
      name: 'Samsung 253L Frost Free Double Door Refrigerator',
      slug: 'samsung-253l-frost-free-refrigerator',
      brand: 'Samsung',
      brandSlug: 'samsung',
      category: 'Refrigerator',
      categorySlug: 'refrigerator',
      modelNumber: 'RT28C3732S8',
      description: 'Digital Inverter technology with toughened glass shelves and optimal fresh food storage.',
      specifications: '{"Capacity":"253 Litres","Type":"Double Door","Energy Rating":"3 Star","Cooling":"Frost Free","Warranty":"1 Year"}',
      mrp: 32990,
      offerPrice: 27990,
      images: [img.product('samsung-fridge-1')],
      isFeatured: true,
      isActive: true,
      createdAt: '2026-01-20',
      updatedAt: '2026-02-15',
    },
    {
      id: 'p3',
      name: 'IFB 7 kg Front Load Washing Machine',
      slug: 'ifb-7kg-front-load-washing-machine',
      brand: 'IFB',
      brandSlug: 'ifb',
      category: 'Washing Machine',
      categorySlug: 'washing-machine',
      modelNumber: 'SERENA WXN 7012',
      description: 'Aqua Energie, Cradle Wash for delicates and 15 wash programs for every fabric.',
      specifications: '{"Capacity":"7 kg","Type":"Front Load","Energy Rating":"5 Star","Programs":"15","Warranty":"4 Years"}',
      mrp: 42990,
      offerPrice: 36490,
      images: [img.product('ifb-washer-1')],
      isFeatured: true,
      isActive: true,
      createdAt: '2026-02-01',
      updatedAt: '2026-03-10',
    },
    {
      id: 'p4',
      name: 'Daikin 1.5 Ton 3 Star Split AC',
      slug: 'daikin-1-5-ton-split-ac',
      brand: 'Daikin',
      brandSlug: 'daikin',
      category: 'Air Conditioner',
      categorySlug: 'air-conditioner',
      modelNumber: 'FTKL50UV16W',
      description: 'Power chill operation, Econo mode and copper condenser for efficient cooling.',
      specifications: '{"Capacity":"1.5 Ton","Type":"Split AC","Energy Rating":"3 Star","Refrigerant":"R-32","Warranty":"1 Year"}',
      mrp: 45990,
      offerPrice: 38990,
      images: [img.product('daikin-ac-1')],
      isFeatured: true,
      isActive: true,
      createdAt: '2026-02-10',
      updatedAt: '2026-03-05',
    },
    {
      id: 'p5',
      name: 'Haier 20L Convection Microwave Oven',
      slug: 'haier-20l-convection-microwave',
      brand: 'Haier',
      brandSlug: 'haier',
      category: 'Microwave',
      categorySlug: 'microwave',
      modelNumber: 'HIL2001CBSH',
      description: 'Convection cooking with auto cook menus and stainless steel cavity.',
      specifications: '{"Capacity":"20 Litres","Type":"Convection","Power":"1200W","Cavity":"Stainless Steel","Warranty":"1 Year"}',
      mrp: 12990,
      offerPrice: 9990,
      images: [img.product('haier-microwave-1')],
      isFeatured: false,
      isActive: true,
      createdAt: '2026-02-15',
      updatedAt: '2026-02-20',
    },
    {
      id: 'p6',
      name: 'Voltas 50L Desert Air Cooler',
      slug: 'voltas-50l-desert-air-cooler',
      brand: 'Voltas',
      brandSlug: 'voltas',
      category: 'Air Cooler',
      categorySlug: 'air-cooler',
      modelNumber: 'Victo 50',
      description: 'High air delivery with honeycomb pads and 3-speed control for hot summers.',
      specifications: '{"Tank Capacity":"50 Litres","Type":"Desert Cooler","Speed Levels":"3","Air Delivery":"3650 m³/hr","Warranty":"1 Year"}',
      mrp: 11990,
      offerPrice: 9490,
      images: [img.product('voltas-cooler-1')],
      isFeatured: false,
      isActive: true,
      createdAt: '2026-03-01',
      updatedAt: '2026-03-01',
    },
    {
      id: 'p7',
      name: 'Blue Star 1 Ton 3 Star Split AC',
      slug: 'blue-star-1-ton-split-ac',
      brand: 'Blue Star',
      brandSlug: 'blue-star',
      category: 'Air Conditioner',
      categorySlug: 'air-conditioner',
      modelNumber: 'IC312YNUR',
      description: 'Precision cooling with hidden display and turbo cool mode.',
      specifications: '{"Capacity":"1 Ton","Type":"Split AC","Energy Rating":"3 Star","Refrigerant":"R-32","Warranty":"1 Year"}',
      mrp: 36990,
      offerPrice: 31990,
      images: [img.product('blue-star-ac-1')],
      isFeatured: false,
      isActive: true,
      createdAt: '2026-03-05',
      updatedAt: '2026-03-05',
    },
    {
      id: 'p8',
      name: 'Samsung 28L Convection Microwave',
      slug: 'samsung-28l-convection-microwave',
      brand: 'Samsung',
      brandSlug: 'samsung',
      category: 'Microwave',
      categorySlug: 'microwave',
      modelNumber: 'CE1041DSB2',
      description: 'Slim fry technology with tandoor and fermentation modes.',
      specifications: '{"Capacity":"28 Litres","Type":"Convection","Power":"1400W","Features":"Slim Fry","Warranty":"1 Year"}',
      mrp: 18990,
      offerPrice: 15490,
      images: [img.product('samsung-microwave-1')],
      isFeatured: true,
      isActive: true,
      createdAt: '2026-03-08',
      updatedAt: '2026-03-08',
    },
  ],
  offers: [
    {
      id: 'o1',
      title: 'TV + Soundbar Combo',
      slug: 'tv-soundbar-combo',
      type: 'combo',
      description: 'Buy any 43"+ LED TV and get soundbar at special combo price.',
      image: img.offer('combo-tv'),
      discountText: 'Save up to ₹8,000',
      validUntil: '2026-06-30',
      isActive: true,
      sortOrder: 1,
    },
    {
      id: 'o2',
      title: 'Build Your Kitchen Bundle',
      slug: 'kitchen-bundle',
      type: 'bundle',
      description: 'Mix chimney, gas stove & mixer grinder for extra savings.',
      image: img.offer('kitchen-bundle'),
      discountText: 'Bundle & Save 15%',
      validUntil: '2026-07-31',
      isActive: true,
      sortOrder: 2,
    },
    {
      id: 'o3',
      title: 'AC Offer Of The Week',
      slug: 'ac-offer-week',
      type: 'weekly',
      description: 'Selected 1.5 Ton split ACs at lowest price this week only.',
      image: img.offer('ac-weekly'),
      discountText: 'From ₹32,990',
      validUntil: '2026-06-21',
      isActive: true,
      sortOrder: 3,
    },
    {
      id: 'o4',
      title: 'Monsoon Festival Sale',
      slug: 'monsoon-festival-sale',
      type: 'festival',
      description: 'Special discounts on refrigerators, washers & RO systems.',
      image: img.offer('festival'),
      discountText: 'Up to 25% Off',
      validUntil: '2026-08-15',
      isActive: true,
      sortOrder: 4,
    },
  ],
};
